# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-04 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wog_workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='type',
        ),
        migrations.AddField(
            model_name='workout',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
