# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wog_workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='start',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
