# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wog_workout', '0002_auto_20171020_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogression',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
