# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wog_workout', '0003_workoutprogression_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'permissions': (('view_session', 'Can view a workout session and its details'), ('modify_session', 'Can modify a workout session and its details'), ('view_progression', 'Can view workout progressions'), ('modify_progression', 'Can add and delete workout progressions'))},
        ),
    ]
