# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wog_workout', '0004_auto_20171023_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
