# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 21:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='athletes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workouttree_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workout.WorkoutTree')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'Staff'), (2, 'One Shot'), (3, 'Private Workout'), (4, 'Public Workout')], default=2)),
                ('amrap', models.IntegerField(default=0)),
                ('emom', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            bases=('workout.workouttree',),
        ),
        migrations.AddField(
            model_name='progression',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Session'),
        ),
    ]
