# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-03 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='athletes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(0, 'Staff'), (1, 'Private Workout'), (2, 'Public Workout')], default=1)),
                ('amrap', models.IntegerField(default=0)),
                ('emom', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_workout', 'Can view the Workout'), ('view_workout_step', 'View create a step on a Workout'), ('add_workout_step', 'Can create a step on a Workout'), ('change_workout_step', 'Can update a step on a Workout'), ('delete_workout_step', 'Can delete a step on a Workout'), ('view_workout_round', 'View create a round on a Workout'), ('add_workout_round', 'Can create a round on a Workout'), ('change_workout_round', 'Can update a round on a Workout'), ('delete_workout_round', 'Can delete a round on a Workout')),
            },
        ),
        migrations.AddField(
            model_name='session',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Workout'),
        ),
        migrations.AddField(
            model_name='progression',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Session'),
        ),
        migrations.AddField(
            model_name='progression',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.Step'),
        ),
        migrations.AddField(
            model_name='progression',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='workout',
            unique_together=set([('creator', 'name')]),
        ),
    ]
