# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'permissions': (('view_workout', 'Can view the Workout'), ('view_workout_round', 'View create a round on a Workout'), ('add_workout_round', 'Can create a round on a Workout'), ('change_workout_round', 'Can update a round on a Workout'), ('delete_workout_round', 'Can delete a round on a Workout'), ('view_workout_step', 'View create a step on a Workout'), ('add_workout_step', 'Can create a step on a Workout'), ('change_workout_step', 'Can update a step on a Workout'), ('delete_workout_step', 'Can delete a step on a Workout'))},
        ),
    ]
