# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('round', '0001_initial'),
        ('workout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progression',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.Step'),
        ),
        migrations.AddField(
            model_name='progression',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workout',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Workout'),
        ),
        migrations.AlterUniqueTogether(
            name='workout',
            unique_together=set([('creator', 'name')]),
        ),
    ]
