# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-18 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20170517_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='time_cap',
            field=models.IntegerField(default=0),
        ),
    ]
