# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-27 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20170323_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'permissions': (('view_workout', 'Can view the Workout'),)},
        ),
    ]
