# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-03 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workout', '0001_initial'),
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoundTreeItem',
            fields=[
                ('workouttree_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workout_tree.WorkoutTree')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_tree_item', to='round.Round')),
            ],
            options={
                'abstract': False,
            },
            bases=('workout_tree.workouttree',),
        ),
        migrations.CreateModel(
            name='StepTreeItem',
            fields=[
                ('workouttree_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workout_tree.WorkoutTree')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_tree_item', to='round.Step')),
            ],
            options={
                'abstract': False,
            },
            bases=('workout_tree.workouttree',),
        ),
        migrations.CreateModel(
            name='WorkoutTreeItem',
            fields=[
                ('workouttree_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='workout_tree.WorkoutTree')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_tree_item', to='workout.Workout')),
            ],
            options={
                'abstract': False,
            },
            bases=('workout_tree.workouttree',),
        ),
    ]
