# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-18 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.IntegerField(choices=[(0, 'Bodyweight'), (1, 'Cross Training'), (2, 'Weightlifting'), (3, 'Powerlifting'), (4, 'TRX')], default=0),
        ),
    ]
