# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-18 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20170518_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='equipement',
            new_name='equipment',
        ),
    ]
