# -*- coding: utf-8 -*-

SESSION_INVITED_GROUP_ID = 0
SESSION_SPECTATOR_GROUP_ID = 1
SESSION_COMPETITOR_GROUP_ID = 3
SESSION_DEFAULT_GROUP_ID = SESSION_COMPETITOR_GROUP_ID


PERMISSION_SESSION_VIEW = 'view_session'
PERMISSION_SESSION_MODIFY = 'modify_session'
PERMISSION_PROGRESS_VIEW = 'view_progression'
PERMISSION_PROGRESS_MODIFY = 'modify_progression'