# -*- coding: utf-8 -*-

SESSION_INVITED_PERMISSION_ID = 0
SESSION_SPECTATOR_PERMISSION_ID = 1
SESSION_COMPETITOR_PERMISSION_ID = 3
SESSION_DEFAULT_PERMISSION_ID = SESSION_COMPETITOR_PERMISSION_ID


PERMISSION_SESSION_INVITED = 'session_view'
PERMISSION_SESSION_SPECTATOR = 'session_watch'
PERMISSION_SESSION_COMPETITOR = 'session_perform'