# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-10 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0002_round_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='round.Round'),
        ),
    ]
