# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-17 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wog_workout', '0001_initial'),
        ('wog_round', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='wog_workout.Workout'),
        ),
    ]
