# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wog_workout', '0002_auto_20171020_2354'),
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSessionPermissionGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('profile_type', models.IntegerField(choices=[(0, 'invited'), (1, 'spectator'), (3, 'competitor')], default=3)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_groups', to='wog_workout.WorkoutSession')),
                ('users', models.ManyToManyField(related_name='session_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('auth.group',),
        ),
        migrations.AlterUniqueTogether(
            name='workoutsessionpermissiongroup',
            unique_together=set([('session', 'profile_type')]),
        ),
    ]
